sudo: required

language: bash

services:
    - docker

before_install:
    - sudo apt-get -y install docker.io debootstrap qemu-user-static debootstrap
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
    - sudo rm /usr/share/docker.io/contrib/mkimage.sh && sudo wget -O /usr/share/docker.io/contrib/mkimage.sh https://gist.githubusercontent.com/meyskens/6890c7e846fa92611848/raw/mkimage.sh && sudo chmod +x /usr/share/docker.io/contrib/mkimage.sh 
    - rm mkimage.sh && ln -s /usr/share/docker.io/contrib/mkimage.sh mkimage.sh
    - ./update.sh
    - docker push meyskens/ubuntu-debootstrap
